### ISSUE TITLE
Issue with NPCs

### ISSUE THREAD

**Issue by idnthvn** [Eufranio/PixelBuilt-Quests#12]
Using Forge 1.12.2 -2847
Sponge 7.1.8 recommended
PixelBuilt 2.1

Issue with NPC, spawning them, they always face south. 
Second issue, i cant kill them or delete the NPC. I tried even in creative and spawning a bunch of items to kill them and no luck.

**Comment by Eufranio** [comment]
Fixed in 3.0+.
