### ISSUE TITLE
Suggestions - Screm

### ISSUE THREAD

**Issue by screm11** [Eufranio/PixelBuilt-Quests#16]
When starting a quest being able to give text from the NPC, as well as multiple options such as close out of the NPC, accept or deny quests that are available from that NPC 

Being able to give messages each time a player completes an objective with updated progress and maybe being able to run commands as well so that we can send messages & show status/progress

Being able to assign multiple quests to 1 NPC, as well as questlines so that players can choose paths of sorts and which quests they want to do (Main quests/side quests of sorts)

**Comment by screm11** [comment]
Also having a hub command such as /pbq quests that pulls up a GUI of available questlines & NPC locations to accept that would be nice

**Comment by screm11** [comment]
Being able to add a cooldown to quests so that you can have daily/weekly/monthly quests would be neat as well. :3

**Comment by Eufranio** [comment]
Please open 1 ticket per suggestion, or related.

**Comment by Eufranio** [comment]
This is what I have implemented so far: 

* Start messages, for when a quest is started (and not neccessarily ran)
* Messages when incrementing objectives, that can be shown via chat or action bar
* Cooldowns

Those will be included in the next release. Prompting a user to accept or not a Quest is not going to be implemented now, but will probably come along with [Takeable Quests](https://github.com/Eufranio/PixelBuilt-Quests/issues/17).
