### ISSUE TITLE
Implement placeholders that can call the status of each quest

### ISSUE THREAD

**Issue by zPr3d** [Eufranio/PixelBuilt-Quests#23]
Placeholder Examples:

- %PBQ_{QUESTLINE}_NEEDED% : If you need to catch 17 more piplups, for a questline, this would return 17.
- %PBQ_{QUESTLINE}_TOTAL% : If  you need to catch 20 piplups total for a questline, this would return 20.
- %PBQ_{QUESTLINE}_PROGRESS% : Would return a combo of the two above, so 17 out of 20.
- %PBQ_{QUESTLINE}_PROGRESS_PERCENTAGE% : Would give the percentage of 17/20.

For quests with multiple requirements
- A way to parse each requirement separately, basically the above placeholders but with a REQ addition as well.
    - %PBQ_{QUESTLINE}_NEEDED_REQ1%
    - %PBQ_{QUESTLINE}_NEEDED_REQ2%

**Comment by Eufranio** [comment]
It's not exactly the way you suggested, but I have added placeholders support in the new (3.4) version. See the docs for it: https://github.com/Eufranio/PixelBuilt-Quests/wiki/Placeholder-support
