### ISSUE TITLE
/pbq info and /pbq status not working

### ISSUE THREAD

**Issue by SuperG14nt** [Eufranio/PixelBuilt-Quests#26]
Whenever I use these commands, it says Error Occurred after executing command: Null.

Here is the server's output for it:

04.03 18:26:33 [Server] Server thread/INFO [nucleus]: SuperG14nt ran the command: /pbq status
04.03 18:26:33 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'pbq status' for source EntityPlayerMP['SuperG14nt'/10, l='ranseiFinish_heightmap', x=1928.18, y=86.00, z=4602.92]: null
04.03 18:26:33 [Server] INFO java.lang.NullPointerException: null
04.03 18:26:33 [Server] INFO at online.pixelbuilt.pbquests.commands.Status.lambda$execute$1(Status.java:40) ~[Status.class:?]
04.03 18:26:33 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265]
04.03 18:26:33 [Server] INFO at online.pixelbuilt.pbquests.commands.Status.execute(Status.java:35) ~[Status.class:?]
04.03 18:26:33 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.3.1-RC4082]
04.03 18:26:33 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.3.1-RC4082]
04.03 18:26:33 [Server] INFO at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.3.1-RC4082]
04.03 18:26:33 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.1-RC4082]
04.03 18:26:33 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
04.03 18:26:33 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.3.1-RC4082]
04.03 18:26:33 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$zlc000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
04.03 18:26:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
04.03 18:26:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
04.03 18:26:33 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
04.03 18:26:33 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:325) [SpongeImplHooks.class:1.12.2-2838-7.3.1-RC4082]
04.03 18:26:33 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
04.03 18:26:33 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
04.03 18:26:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by Eufranio** [comment]
Should be fixed in 3.4.
