### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by unovalegends** [Eufranio/PixelBuilt-Quests#3]
Does this plugin need another plugin in order for it to work?

**Comment by Eufranio** [comment]
No, you don't need anything else to run this, just a MongoDB database. Define `plugin isn't working`... any errors?

**Comment by unovalegends** [comment]
Well for starters it literally kicks all players out of the server and the server randomly restarts.

Here a message from my console
https://hastebin.com/urotocijex.css

**Comment by Eufranio** [comment]
Irrelevant for the new version, please update!
