### ISSUE TITLE
ByteItems support

### ISSUE THREAD

**Issue by galoti** [Eufranio/PixelBuilt-Quests#8]
Hello!! Could you add support to ByteItems ? ByteItems saves ItemStacks to a database. Several plugins implement ByteItems to have a central database with ItemStack definitions. ByteItems has an API to retrieve ItemStacks:

https://github.com/randombyte-developer/byte-items/blob/20d456db28b90b2436eb30eba19fe02ff1f8afda/src/main/kotlin/de/randombyte/byteitems/ByteItemsApi.kt#L13

https://ore.spongepowered.org/RandomByte/ByteItems

https://github.com/randombyte-developer/byte-items

**Comment by Eufranio** [comment]
Will do that in this rewrite.

**Comment by galoti** [comment]
Ok, thanks!

**Comment by Eufranio** [comment]
Added a task for ByteItems (`pbq:byteitem`).
