### ISSUE TITLE
NPCs cause entity render crash

### ISSUE THREAD

**Issue by MCPHKevin** [Eufranio/PixelBuilt-Quests#9]
Here is the full report: https://hastebin.com/kirexikino.coffeescript
And another report from my friend: https://pastebin.com/ei7rLkHE

If you're alone, the NPC will not cause a crash.
If two players are near the NPC, it will almost always crash.

Using spongeforge-1.12.2-2768-7.1.5 on forge-1.12.2-14.23.5.2836-universal on a server.

**Comment by Eufranio** [comment]
Irrelevant for the new version, please update!
